---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-kafka-user-passwords
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: kafka-30.1.4
type: Opaque
data:
  client-passwords: "YmgzdXNYeUVJcg=="
  system-user-password: "YmgzdXNYeUVJcg=="
  inter-broker-password: "elhhUlBNN044UA=="
  controller-password: "RTNOcklZS0pORA=="
---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-kafka-kraft-cluster-id
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: kafka-30.1.4
type: Opaque
data:
  kraft-cluster-id: "dnl0WDhFWDNHWlg3TnhUNDJsaTl6VQ=="
