---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: message-broker-kafka-user-passwords
  namespace: nexus-deva
  labels:
    app.kubernetes.io/instance: message-broker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.1
    helm.sh/chart: kafka-30.1.8
type: Opaque
data:
  client-passwords: "SDhucXhpWU04MQ=="
  system-user-password: "SDhucXhpWU04MQ=="
  inter-broker-password: "eFBGUDUzMWlvRg=="
  controller-password: "UktIYTdaZE5HNA=="
---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: message-broker-kafka-kraft-cluster-id
  namespace: nexus-deva
  labels:
    app.kubernetes.io/instance: message-broker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.1
    helm.sh/chart: kafka-30.1.8
type: Opaque
data:
  kraft-cluster-id: "bTgxdGpHSUdMd3BWYXdkRG51WGExVQ=="
