---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: message-broker-kafka-user-passwords
  namespace: "nexus-platform"
  labels:
    app.kubernetes.io/instance: message-broker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.1
    helm.sh/chart: kafka-30.1.8
type: Opaque
data:
  client-passwords: "NkcyanFxV29kSw=="
  system-user-password: "NkcyanFxV29kSw=="
  inter-broker-password: "Y3dNU2s3cnpSRA=="
  controller-password: "RlNpaWpsZUNLbw=="
---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: message-broker-kafka-kraft-cluster-id
  namespace: "nexus-platform"
  labels:
    app.kubernetes.io/instance: message-broker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.1
    helm.sh/chart: kafka-30.1.8
type: Opaque
data:
  kraft-cluster-id: "RHprZkVSSlJlMEp4cm42N3RsVGg3cQ=="
