apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-kafka
  namespace: message-broker
  labels:
    app: apache-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-kafka
  template:
    metadata:
      labels:
        app: apache-kafka
    spec:
      containers:
      - name: apache-kafka
        image: apache/kafka:3.9.0
        ports:
        - containerPort: 9092
